import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";
import Head from "next/head";
import Body from "./Body";
import Home from "./page";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className=" overflow-x-hidden overflow-y-auto">
      <body>
        <Navbar />
        <div className="flex justify-center items-center ">{children}</div>
      </body>
    </html>
  );
}
